### ISSUE TITLE
Sync column information with properties in notes

### ISSUE THREAD

**Issue by Aspect004** [decaf-dev/obsidian-dataloom#663]
### Problem

-

### Solution

-

### Additional details

![dbtemplatefilternodither](https://github.com/trey-wallis/obsidian-dataloom/assets/141172418/cdddbbce-663e-433e-9a25-3f944062c3b7)

**Comment by trey-wallis** [comment]
Hi @Aspect004. What do you mean by file parameters? The front matter or something else?

**Comment by Aspect004** [comment]
> Hi @Aspect004. What do you mean by file parameters? The front matter or something else?

Hi @trey-wallis. What I mean by file parameters is any field you enter in the rows beside the **first file column** to appear inside the file as front matter when you open the file.

**Comment by Aspect004** [comment]
Hi @trey-wallis! I feel that you didn't understand my feature request. 😅

**Comment by trey-wallis** [comment]
Oops. I tagged the wrong issue

**Comment by trey-wallis** [comment]
No. Could you explain it more?

**Comment by Aspect004** [comment]
![Screenshot_20230821-071611_Photos~2.jpg](https://github.com/trey-wallis/obsidian-dataloom/assets/141172418/14b34853-b539-44f3-8887-0c65e4a76ea7)

What I mean is, that in Notion the first column (highlighted in red) must include only files. And the other columns (highlighted in green) are the metadata or frontmatter for those files. Do you get what I am trying to say?

**Comment by FeralFlora** [comment]
This would be nice as an optional feature, either applied to a whole loom, or single columns as Lookup fields, similar to the [feature of Airtable](https://support.airtable.com/docs/lookup-field-overview). In that case, the first column would be a file column.

However, there are many usecases where the prerequsite of each row referencing a file is not desirable. That's why I stress that this should be an optional feature or mode.

I must note that what you write in the title doesn't seem to match your preceding comment. The title sounds more like you want to have Properties / frontmatter on the loom / table itself.

**Comment by Aspect004** [comment]
> This would be nice as an optional feature, either applied to a whole loom, or single columns as Lookup fields, similar to the [feature of Airtable](https://support.airtable.com/docs/lookup-field-overview). In that case, the first column would be a file column.
> 
> However, there are many usecases where the prerequsite of each row referencing a file is not desirable. That's why I stress that this should be an optional feature or mode.
> 
> I must note that what you write in the title doesn't seem to match your preceding comment. The title sounds more like you want to have Properties / frontmatter on the loom / table itself.

This is exactly what I am trying to say! I am sorry I tried as hard as I can to articulate what I mean, which ended up understated. 😅

**Comment by acook** [comment]
This sounds similar to the DB Folder plugin?

I feel like Loom has a lot of nice features, but being able to sync column information with properties in notes is really handy.
